
version: 2.1


jobs:

  build:

    docker:
      - image: cimg/node:13.8.0

    steps:
      - checkout
      - run:
          name: install packages
          command: npm i

      - run:
          name: Build Project
          command: npm run lint

  test:

    docker:
      - image: cimg/node:13.8.0

    steps:
      - checkout
      - run:
          name: install packages
          command: npm install

      - run:
          name: Run Tests
          command: npm run test

  analyze:

    docker:
      - image: cimg/node:13.8.0

    steps:
      - checkout
      - run:
          name: install packages
          command: npm install

      - run:
          name: Analyze Project
          command: npm audit

workflows:
  orb-free-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
